# StyLua Configuration for PercyBrain
# Modern Lua formatter - https://github.com/JohnnyMorganz/StyLua

# Column width for line wrapping
column_width = 120

# Line endings
line_endings = "Unix"

# Indentation
indent_type = "Spaces"
indent_width = 2

# Quote style
quote_style = "AutoPreferDouble"

# Call parentheses
call_parentheses = "Always"

# Collapse simple statements
collapse_simple_statement = "Never"

[sort_requires]
# Sort require statements
enabled = false
