# Selene Configuration for PercyBrain
# Modern Lua linter - https://github.com/Kampfkarren/selene

# Standard library to use (lua51 for LuaJIT compatibility)
# vim globals are allowed via [config] section below
std = "lua51"

# Additional globals allowed
[config.globals]
# Neovim global object (allow any key access)
vim = "allow_any_key"
[rules]
# Warn about unused variables
unused_variable = "warn"

# Allow undefined globals (vim is always global in Neovim)
undefined_variable = "allow"

# Warn about shadowing variables
shadowing = "warn"

# Allow unscoped variables (vim is always global in Neovim)
unscoped_variables = "allow"

# Error on empty code blocks
empty_if = "deny"
empty_loop = "deny"

# Warn on incorrect type usage
incorrect_standard_library_use = "deny"

# Allow mixed tables (common in Neovim plugin specs)
mixed_table = "allow"

# Allow vim global usage
global_usage = "allow"
