name: Lua Quality Checks

on:
  push:
    branches: ['**']
    paths:
      - 'lua/**/*.lua'
      - '.stylua.toml'
      - 'selene.toml'
      - '.luarc.json'
      - '.github/workflows/lua-quality.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'lua/**/*.lua'

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Lua tools
        id: cache-lua-tools
        uses: actions/cache@v4
        with:
          path: ~/.local/bin
          key: lua-tools-${{ runner.os }}-stylua-2.3.0-selene-0.29.0

      - name: Install Lua quality tools
        if: steps.cache-lua-tools.outputs.cache-hit != 'true'
        run: |
          chmod +x scripts/install-lua-tools.sh
          ./scripts/install-lua-tools.sh --ci

      - name: Add tools to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify tool installation
        run: |
          stylua --version
          selene --version

      - name: Check formatting with StyLua
        run: |
          echo "::group::StyLua Formatting Check"
          stylua --check lua/
          echo "::endgroup::"

      - name: Lint with Selene
        run: |
          echo "::group::Selene Linting"
          selene lua/
          echo "::endgroup::"

      - name: Comment on PR (if failure)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            let comment = '## ❌ Lua Quality Checks Failed\\n\\n';
            comment += '**Failed checks:**\\n';
            comment += '- StyLua formatting or\\n';
            comment += '- Selene linting\\n\\n';
            comment += '**Fix locally:**\\n';
            comment += '```bash\\n';
            comment += '# Format code\\n';
            comment += 'stylua lua/\\n\\n';
            comment += '# Check linting\\n';
            comment += 'selene lua/\\n\\n';
            comment += '# Then commit\\n';
            comment += 'git add -A\\n';
            comment += 'git commit --amend --no-edit\\n';
            comment += '```\\n\\n';
            comment += '**Or install tools:**\\n';
            comment += '```bash\\n';
            comment += './scripts/install-lua-tools.sh\\n';
            comment += '```\\n';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
