name: PercyBrain Tests

on:
  push:
    branches: ['**']
    paths:
      - 'tests/**'
      - 'lua/config/zettelkasten.lua'
      - 'lua/plugins/ollama.lua'
      - 'lua/plugins/sembr.lua'
      - 'claudedocs/**'
  pull_request:
    branches: [main, master]
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Display Neovim version
        run: nvim --version

      - name: Make test scripts executable
        run: chmod +x tests/*.sh

      - name: Run PercyBrain quick health check
        id: quick-check
        run: |
          echo "::group::Quick Health Check"
          cd tests
          ./quick-check.sh || echo "Some optional dependencies missing (expected in CI)"
          echo "::endgroup::"

      - name: Run PercyBrain full test suite
        id: full-tests
        run: |
          echo "::group::Full Test Suite"
          cd tests
          ./percybrain-test.sh
          echo "::endgroup::"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: percybrain-test-report
          path: tests/output/test-report-*.txt
          retention-days: 30

      - name: Comment test results on PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const testStatus = '${{ steps.full-tests.outcome }}';
            const icon = testStatus === 'success' ? '✅' : '❌';

            let comment = `## ${icon} PercyBrain Tests - ${testStatus}\n\n`;

            if (testStatus === 'success') {
              comment += '**All 36 tests passed!** 🎉\n\n';
              comment += 'PercyBrain system is fully operational.';
            } else {
              comment += '**Some tests failed.** Please review the logs above.\n\n';
              comment += '**Run tests locally:**\n';
              comment += '```bash\n';
              comment += 'cd tests\n';
              comment += './percybrain-test.sh\n';
              comment += '```\n';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
